### ISSUE TITLE
`process.check` returns a `None` when clients expect a 3 item tuple

### ISSUE THREAD

**Issue by alfredodeza** [alfredodeza/remoto#3]
When a timeout occurs it returns a None, breakage ensues because the client expects a three item tuple.  

    [node2][INFO  ] Running command: sudo ceph --cluster=ceph osd stat --format=json
    [node2][WARNIN] No data was received after 300 seconds, disconnecting...
    Traceback (most recent call last):
      File "/Users/alfredo/.virtualenvs/ceph-deploy/bin/ceph-deploy", line 8, in <module>
        load_entry_point('ceph-deploy==1.4.0', 'console_scripts', 'ceph-deploy')()
      File "/Users/alfredo/python/ceph-deploy/ceph_deploy/util/decorators.py", line 62, in newfunc
        return f(*a, **kw)
      File "/Users/alfredo/python/ceph-deploy/ceph_deploy/cli.py", line 147, in main
        return args.func(args)
      File "/Users/alfredo/python/ceph-deploy/ceph_deploy/osd.py", line 532, in osd
        activate(args, cfg)
      File "/Users/alfredo/python/ceph-deploy/ceph_deploy/osd.py", line 338, in activate
        catch_osd_errors(distro.conn, distro.conn.logger, args)
      File "/Users/alfredo/python/ceph-deploy/ceph_deploy/osd.py", line 152, in catch_osd_errors
        status = osd_status_check(conn, args.cluster)
      File "/Users/alfredo/python/ceph-deploy/ceph_deploy/osd.py", line 129, in osd_status_check
        command,
    TypeError: 'NoneType' object is not iterable

**Comment by onyb** [comment]
Would raising a custom exception in [L271](https://github.com/alfredodeza/remoto/blob/master/remoto/process.py#L171) of `process.py` help? The block just does a bare `return`.

**Comment by alfredodeza** [comment]
Fixed with 38f4d7a6f9b004c7966d6635eb694b4a72128bc3
