### ISSUE TITLE
Usage of eval vs ast.literal_eval

### ISSUE THREAD

**Issue by psukys** [alfredodeza/remoto#40]
I've been using some linters for my code base and they report warnings on `eval` usage and that `ast.literal_eval` should be a safe replacement. Though, whenever I replace, I receive the following error:
```
Traceback (most recent call last):
  File "~/.venv/lib/python3.6/site-packages/remoto/connection.py", line 137, in wrapper_continuous
    for item in self.channel:
  File "~/.venv/lib/python3.6/site-packages/execnet/gateway_base.py", line 746, in next
    return self.receive()
  File "~/.venv/lib/python3.6/site-packages/execnet/gateway_base.py", line 737, in receive
    raise self._getremoteerror() or EOFError()
execnet.gateway_base.RemoteError: Traceback (most recent call last):
  File "<string>", line 1072, in executetask
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 156, in <module>
  File "/usr/lib/python3.6/ast.py", line 85, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.6/ast.py", line 84, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Call object at 0xb69b4790>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.venv/lib/python3.6/site-packages/remoto/connection.py", line 151, in wrapper_continuous
    raise RuntimeError(exc_line)
RuntimeError: ValueError: malformed node or string: <_ast.Call object at 0xb69b4790>
```

**Comment by psukys** [comment]
Ok, I think this is my misunderstanding on `ast` usage.
Proper usage is described [here](http://greentreesnakes.readthedocs.io/en/latest/tofrom.html):
```python
>>> tree = ast.parse("print('hello world')")
>>> tree
<_ast.Module object at 0x9e3df6c>
>>> exec(compile(tree, filename="<ast>", mode="exec"))
hello world

``
